# Debugging Python Code
- Try and Else Block
- Pdb
- set trace method

## Common Python Errors
- `SyntaxError` The programmermade a mistake in the structure of a statement or expression. 
- `NameError` This usually occurs when a variable is not defined or it hasn't been assigned yet.
- `TypeError` This usually occurs when an operation or function is applied to a wrong type.
- `IndexError` This occurs when we are trying to access an element in a list using invalid index.
- `ValueError`  This occurs when a built in operation or function receives an arguement that has the right type but an inappropiate value
- `KeyError` This occurs when a dictionary doesn't have a specific key.
- `AttributeError` This occurs when a variable doesn't have an attribute. 
- Exceptions:  a logic error leads to a runtime error that causes the program to terminate. In some cases, logic errors lead to very bad situations such as trying to divide by zero or trying to access an item in a list where the index of the item is outside the bounds of the list.

## Handling Errors: try & except
- most programming languages provide a way to deal with these errors that will allow the programmer to have some type of intervention if they so choose. In addition, programmers can create their own exceptions if they detect a situation in the program execution that warrants it.
- When an exception occurs, we say that it has been “raised.” You can “handle” the exception that has been raised by using a try statement. 

- For example, consider the following session that asks the user for an integer and then calls the square root function from the math library. If the user enters a value that is greater than or equal to 0, the print will show the square root. However, if the user enters a negative value, the square root function will report a ValueError exception.
```Python3
anumber = int(input("Please enter an integer "))
Please enter an integer -23
print(math.sqrt(anumber))
ValueError: math domain error
```
We can handle this exception by calling the print function from within a try block. A corresponding except block “catches” the exception and prints a message back to the user in the event that an exception occurs. For example:
```Python3
try:
    print(math.sqrt(anumber))
except:
    print("Using absolute value instead")
```

## raise statement
- It is also possible for a programmer to cause a runtime exception by using the raise -statement. 
- Note that the program would still terminate but now the exception that caused the termination is something explicitly created by the programmer.
- . For example, instead of calling the square root function with a negative number, we could have checked the value first and then raised our own exception:
```Python3
if anumber < 0:
    raise RuntimeError("You can't use a negative number")
else:
    print(math.sqrt(anumber))

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
RuntimeError: You can't use a negative number
```

## Debugging our code using `PDB`

- In order to set a breakpoint we use `pdb.set_trace()`
- After setting a breakpoint then we can go line by line through our code.

#### Common `PDB` commands
- `l` List 
- `n` next line
- `p` print
- `c` continue
